fail_fast: true
repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: poetry run black
      language: system
      types: [file, python]
      exclude: '^.*migrations.*$'
    - id: isort
      name: isort
      entry: poetry run isort
      language: system
      types: [file, python]
      exclude: '^.*migrations.*$'



#- repo: git://github.com/pre-commit/pre-commit-hooks
#  rev: v2.5.0
#  hooks:
#    - id: trailing-whitespace
#    - id: check-merge-conflict
#    - id: debug-statements
#    - id: flake8
#      exclude: '^.*migrations.*$'
#      additional_dependencies: [
#        'flake8-blind-except',
#        'flake8-comprehensions',
#        'flake8-pep3101',
#      ]
#- repo: https://github.com/pre-commit/mirrors-mypy
#  rev: v1.9.0
#  hooks:
#    - id: mypy
#      args: [--follow-imports=silent, --ignore-missing-imports]