version: '3.9'

services:
  app:
    container_name: hr_app
    image: hr-app
    restart: unless-stopped
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile
    command: >
      bash -c "python -m uvicorn app.main:app --reload"
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ${PWD}/:/humanRecognizer
    env_file:
      - ${PWD}/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - human-recognizer-net


networks:
  human-recognizer-net:
    driver: bridge
