services:
  tests:
    container_name: hr_tests
    image: hr-app
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile
    command: >
      bash -c "pytest app &&
      rm -r tmp"
    volumes:
      - ${PWD}/:/humanRecognizer
    env_file:
      - ${PWD}/.env
    environment:
      - TESTS_RUNNING=True
    depends_on:
      postgres:
        condition: service_healthy
#      redis:
#        condition: service_healthy
    networks:
      - human-recognizer-net


networks:
  human-recognizer-net:
    driver: bridge
